# Makefile.config for github-create-repo install

# HOME_PATH needs to point to your home directory (~)
HOME_PATH = /home/jsw65

# BIN_PATH and COMMAND_NAME can be changed if needed
COMMAND_NAME = github-create-repo
BIN_PATH = /usr/local/bin